### ISSUE TITLE
jekyll website / the Gemfile

### ISSUE THREAD

**Issue by a-schaefers** [cooslug/cooslug.github.io#6]
Is the [Gemfile](https://github.com/cooslug/cooslug.github.io/blob/master/Gemfile) as it stands now, sane?

Particularly, I commented what was there by default,
`# gem "jekyll", "~> 3.8.1"`
And I added this bit that i found from https://jekyllrb.com/docs/github-pages/
`gem "github-pages", group: :jekyll_plugins`

My workflow I'm running is: (I would like to feedback to know if I am doing jekyll, 'right')

bundle update (to keep the whole of jekyll website up to date?)
bundle exec jekyll serve (while modifying the website locally)
bundle exec jekyll build (seems unnecessary since we are not pushing _site and github seems to be building the website automagically)
git add / commit / push (make the changes live)

Is there anything else I should know?

Thanks

**Comment by bayprogrammer** [comment]
I believe the change you made to the Gemfile was the right way to go. Based on reading #5 it looks like the `github-pages` gem requires a specific version of Jekyll that conflicted with the `~> 3.8.1` version specification. Since we're using github pages, letting it control the version of Jekyll seems reasonable to me.

As for the workflow, that all looks correct. Just to clarify, `bundle update` is for updating the dependencies of the `Gemfile.lock` itself and not necessary during the usual workflow (until we want to update the deps). `serve` is probably the most relevant command for us when updating the site on our local machines.

**Comment by a-schaefers** [comment]
Thankyou for the clarification. What is best practice for bundle update, the jekyll doc just says "run bundle update often" lol

**Comment by bayprogrammer** [comment]
Best bet is to run bundle update often. :trollface:

**Comment by bayprogrammer** [comment]
We can probably run it once or twice per month, just to keep on top of things. That should be often enough. I think also that GitHub will pester us if one of the project deps in the Gemfile.lock have a known security flaw. Since we're just processing our own input and letting GH convert it to HTML automatically, there's low risk to begin with (but keeping things up to date is still a good idea).

**Comment by a-schaefers** [comment]
Got it.
